// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: session.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    transfer_id,
    chunk_count,
    status,
    expires_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, transfer_id, chunk_count, chunks_completed, status, created_at, updated_at, expires_at
`

type CreateSessionParams struct {
	TransferID uuid.UUID `json:"transfer_id"`
	ChunkCount int32     `json:"chunk_count"`
	Status     string    `json:"status"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TransferID,
		arg.ChunkCount,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.ChunkCount,
		&i.ChunksCompleted,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, transfer_id, chunk_count, chunks_completed, status, created_at, updated_at, expires_at FROM sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.ChunkCount,
		&i.ChunksCompleted,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionByTransferID = `-- name: GetSessionByTransferID :one
SELECT id, transfer_id, chunk_count, chunks_completed, status, created_at, updated_at, expires_at FROM sessions
WHERE transfer_id = $1
LIMIT 1
`

func (q *Queries) GetSessionByTransferID(ctx context.Context, transferID uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTransferID, transferID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.ChunkCount,
		&i.ChunksCompleted,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateSessionChunksCompleted = `-- name: UpdateSessionChunksCompleted :one
UPDATE sessions
SET chunks_completed = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, transfer_id, chunk_count, chunks_completed, status, created_at, updated_at, expires_at
`

type UpdateSessionChunksCompletedParams struct {
	ID              uuid.UUID `json:"id"`
	ChunksCompleted int32     `json:"chunks_completed"`
}

func (q *Queries) UpdateSessionChunksCompleted(ctx context.Context, arg UpdateSessionChunksCompletedParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionChunksCompleted, arg.ID, arg.ChunksCompleted)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.ChunkCount,
		&i.ChunksCompleted,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :one
UPDATE sessions
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, transfer_id, chunk_count, chunks_completed, status, created_at, updated_at, expires_at
`

type UpdateSessionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionStatus, arg.ID, arg.Status)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.ChunkCount,
		&i.ChunksCompleted,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
