// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: transfer.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
    user_id,
    name,
    size,
    content_type,
    encrypted_metadata,
    access_token,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, name, size, content_type, encrypted_metadata, access_token, expires_at, created_at, updated_at, downloaded, download_count
`

type CreateTransferParams struct {
	UserID            uuid.UUID `json:"user_id"`
	Name              string    `json:"name"`
	Size              int64     `json:"size"`
	ContentType       string    `json:"content_type"`
	EncryptedMetadata []byte    `json:"encrypted_metadata"`
	AccessToken       string    `json:"access_token"`
	ExpiresAt         time.Time `json:"expires_at"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.UserID,
		arg.Name,
		arg.Size,
		arg.ContentType,
		arg.EncryptedMetadata,
		arg.AccessToken,
		arg.ExpiresAt,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Size,
		&i.ContentType,
		&i.EncryptedMetadata,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Downloaded,
		&i.DownloadCount,
	)
	return i, err
}

const deleteExpiredTransfers = `-- name: DeleteExpiredTransfers :exec
DELETE FROM transfers
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTransfers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTransfers)
	return err
}

const getTransferByAccessToken = `-- name: GetTransferByAccessToken :one
SELECT id, user_id, name, size, content_type, encrypted_metadata, access_token, expires_at, created_at, updated_at, downloaded, download_count FROM transfers
WHERE access_token = $1
LIMIT 1
`

func (q *Queries) GetTransferByAccessToken(ctx context.Context, accessToken string) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByAccessToken, accessToken)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Size,
		&i.ContentType,
		&i.EncryptedMetadata,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Downloaded,
		&i.DownloadCount,
	)
	return i, err
}

const getTransferByID = `-- name: GetTransferByID :one
SELECT id, user_id, name, size, content_type, encrypted_metadata, access_token, expires_at, created_at, updated_at, downloaded, download_count FROM transfers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTransferByID(ctx context.Context, id uuid.UUID) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByID, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Size,
		&i.ContentType,
		&i.EncryptedMetadata,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Downloaded,
		&i.DownloadCount,
	)
	return i, err
}

const getUserTransfers = `-- name: GetUserTransfers :many
SELECT id, user_id, name, size, content_type, encrypted_metadata, access_token, expires_at, created_at, updated_at, downloaded, download_count FROM transfers
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserTransfers(ctx context.Context, userID uuid.UUID) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, getUserTransfers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Size,
			&i.ContentType,
			&i.EncryptedMetadata,
			&i.AccessToken,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Downloaded,
			&i.DownloadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransferDownloadStatus = `-- name: UpdateTransferDownloadStatus :one
UPDATE transfers
SET downloaded = true,
    download_count = download_count + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, size, content_type, encrypted_metadata, access_token, expires_at, created_at, updated_at, downloaded, download_count
`

func (q *Queries) UpdateTransferDownloadStatus(ctx context.Context, id uuid.UUID) (Transfer, error) {
	row := q.db.QueryRow(ctx, updateTransferDownloadStatus, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Size,
		&i.ContentType,
		&i.EncryptedMetadata,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Downloaded,
		&i.DownloadCount,
	)
	return i, err
}
