// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    device_id,
    fingerprint
) VALUES (
    $1, $2
) RETURNING id, device_id, fingerprint, created_at, updated_at, last_seen_at
`

type CreateUserParams struct {
	DeviceID    string `json:"device_id"`
	Fingerprint string `json:"fingerprint"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.DeviceID, arg.Fingerprint)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByDeviceID = `-- name: GetUserByDeviceID :one
SELECT id, device_id, fingerprint, created_at, updated_at, last_seen_at FROM users
WHERE device_id = $1
LIMIT 1
`

func (q *Queries) GetUserByDeviceID(ctx context.Context, deviceID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDeviceID, deviceID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByFingerprint = `-- name: GetUserByFingerprint :one
SELECT id, device_id, fingerprint, created_at, updated_at, last_seen_at FROM users
WHERE fingerprint = $1
LIMIT 1
`

func (q *Queries) GetUserByFingerprint(ctx context.Context, fingerprint string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFingerprint, fingerprint)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const updateUserLastSeen = `-- name: UpdateUserLastSeen :one
UPDATE users
SET last_seen_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, device_id, fingerprint, created_at, updated_at, last_seen_at
`

func (q *Queries) UpdateUserLastSeen(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLastSeen, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
