// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID              uuid.UUID `json:"id"`
	TransferID      uuid.UUID `json:"transfer_id"`
	ChunkCount      int32     `json:"chunk_count"`
	ChunksCompleted int32     `json:"chunks_completed"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	ExpiresAt       time.Time `json:"expires_at"`
}

type Transfer struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	Name              string    `json:"name"`
	Size              int64     `json:"size"`
	ContentType       string    `json:"content_type"`
	EncryptedMetadata []byte    `json:"encrypted_metadata"`
	AccessToken       string    `json:"access_token"`
	ExpiresAt         time.Time `json:"expires_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	Downloaded        bool      `json:"downloaded"`
	DownloadCount     int32     `json:"download_count"`
}

type User struct {
	ID          uuid.UUID `json:"id"`
	DeviceID    string    `json:"device_id"`
	Fingerprint string    `json:"fingerprint"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	LastSeenAt  time.Time `json:"last_seen_at"`
}
