// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: webrtc.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebRTCSession = `-- name: CreateWebRTCSession :one
INSERT INTO webrtc_sessions (
    transfer_id,
    initiator_id,
    room_id,
    status,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, transfer_id, initiator_id, receiver_id, room_id, sdp_offer, status, created_at, updated_at, expires_at
`

type CreateWebRTCSessionParams struct {
	TransferID  uuid.UUID `json:"transfer_id"`
	InitiatorID uuid.UUID `json:"initiator_id"`
	RoomID      string    `json:"room_id"`
	Status      string    `json:"status"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateWebRTCSession(ctx context.Context, arg CreateWebRTCSessionParams) (WebrtcSession, error) {
	row := q.db.QueryRow(ctx, createWebRTCSession,
		arg.TransferID,
		arg.InitiatorID,
		arg.RoomID,
		arg.Status,
		arg.ExpiresAt,
	)
	var i WebrtcSession
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.InitiatorID,
		&i.ReceiverID,
		&i.RoomID,
		&i.SdpOffer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredWebRTCSessions = `-- name: DeleteExpiredWebRTCSessions :exec
DELETE FROM webrtc_sessions
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredWebRTCSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredWebRTCSessions)
	return err
}

const getWebRTCSessionByRoomID = `-- name: GetWebRTCSessionByRoomID :one
SELECT id, transfer_id, initiator_id, receiver_id, room_id, sdp_offer, status, created_at, updated_at, expires_at FROM webrtc_sessions
WHERE room_id = $1
LIMIT 1
`

func (q *Queries) GetWebRTCSessionByRoomID(ctx context.Context, roomID string) (WebrtcSession, error) {
	row := q.db.QueryRow(ctx, getWebRTCSessionByRoomID, roomID)
	var i WebrtcSession
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.InitiatorID,
		&i.ReceiverID,
		&i.RoomID,
		&i.SdpOffer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getWebRTCSessionByTransferID = `-- name: GetWebRTCSessionByTransferID :one
SELECT id, transfer_id, initiator_id, receiver_id, room_id, sdp_offer, status, created_at, updated_at, expires_at FROM webrtc_sessions
WHERE transfer_id = $1
LIMIT 1
`

func (q *Queries) GetWebRTCSessionByTransferID(ctx context.Context, transferID uuid.UUID) (WebrtcSession, error) {
	row := q.db.QueryRow(ctx, getWebRTCSessionByTransferID, transferID)
	var i WebrtcSession
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.InitiatorID,
		&i.ReceiverID,
		&i.RoomID,
		&i.SdpOffer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateWebRTCSessionOffer = `-- name: UpdateWebRTCSessionOffer :one
UPDATE webrtc_sessions
SET sdp_offer = $2,
    updated_at = NOW()
WHERE room_id = $1
RETURNING id, transfer_id, initiator_id, receiver_id, room_id, sdp_offer, status, created_at, updated_at, expires_at
`

type UpdateWebRTCSessionOfferParams struct {
	RoomID   string      `json:"room_id"`
	SdpOffer pgtype.Text `json:"sdp_offer"`
}

func (q *Queries) UpdateWebRTCSessionOffer(ctx context.Context, arg UpdateWebRTCSessionOfferParams) (WebrtcSession, error) {
	row := q.db.QueryRow(ctx, updateWebRTCSessionOffer, arg.RoomID, arg.SdpOffer)
	var i WebrtcSession
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.InitiatorID,
		&i.ReceiverID,
		&i.RoomID,
		&i.SdpOffer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateWebRTCSessionReceiver = `-- name: UpdateWebRTCSessionReceiver :one
UPDATE webrtc_sessions
SET receiver_id = $2,
    status = 'joined',
    updated_at = NOW()
WHERE room_id = $1
RETURNING id, transfer_id, initiator_id, receiver_id, room_id, sdp_offer, status, created_at, updated_at, expires_at
`

type UpdateWebRTCSessionReceiverParams struct {
	RoomID     string      `json:"room_id"`
	ReceiverID pgtype.UUID `json:"receiver_id"`
}

func (q *Queries) UpdateWebRTCSessionReceiver(ctx context.Context, arg UpdateWebRTCSessionReceiverParams) (WebrtcSession, error) {
	row := q.db.QueryRow(ctx, updateWebRTCSessionReceiver, arg.RoomID, arg.ReceiverID)
	var i WebrtcSession
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.InitiatorID,
		&i.ReceiverID,
		&i.RoomID,
		&i.SdpOffer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateWebRTCSessionStatus = `-- name: UpdateWebRTCSessionStatus :one
UPDATE webrtc_sessions
SET status = $2,
    updated_at = NOW()
WHERE room_id = $1
RETURNING id, transfer_id, initiator_id, receiver_id, room_id, sdp_offer, status, created_at, updated_at, expires_at
`

type UpdateWebRTCSessionStatusParams struct {
	RoomID string `json:"room_id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateWebRTCSessionStatus(ctx context.Context, arg UpdateWebRTCSessionStatusParams) (WebrtcSession, error) {
	row := q.db.QueryRow(ctx, updateWebRTCSessionStatus, arg.RoomID, arg.Status)
	var i WebrtcSession
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.InitiatorID,
		&i.ReceiverID,
		&i.RoomID,
		&i.SdpOffer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
